services:
  - type: web
    name: cvet-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production

  - type: web
    name: cvet-web
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    plan: free
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: API_URL
        value: https://cvet-api.onrender.com
