function itens(grupo, nomes) {
  return nomes.split('|').map((nome) => ({ nome, especie: 'CANINO', grupoFci: grupo }));
}

export const racasCaninas = [
  { nome: 'Sem raça definida (SRD)', especie: 'CANINO', grupoFci: null },
  ...itens(1, 'Australian Cattle Dog|Australian Kelpie|Australian Shepherd|Bearded Collie|Beauceron|Belgian Shepherd Dog|Bergamasco Shepherd Dog|Berger Blanc Suisse|Border Collie|Bouvier des Ardennes|Bouvier des Flandres|Briard|Cardigan Welsh Corgi|Collie Rough|Collie Smooth|Croatian Sheepdog|Czechoslovakian Wolfdog|Dutch Shepherd|German Shepherd Dog|Komondor|Kuvasz|Maremma Sheepdog|Miniature American Shepherd|Mudi|Old English Sheepdog|Pembroke Welsh Corgi|Polish Lowland Sheepdog|Polish Tatra Sheepdog|Puli|Pumi|Pyrenean Shepherd|Saarloos Wolfdog|Schapendoes|Schipperke|Shetland Sheepdog|Slovakian Chuvach|Swedish Vallhund'),
  ...itens(2, 'Affenpinscher|Anatolian Shepherd Dog|Appenzeller Sennenhund|Bernese Mountain Dog|Black Russian Terrier|Boerboel|Boxer|Broholmer|Bullmastiff|Cane Corso|Central Asian Shepherd Dog|Cimarron Uruguayo|Dobermann|Dogo Argentino|Dogue de Bordeaux|English Mastiff|Entlebucher Mountain Dog|Fila Brasileiro|Great Dane|Great Pyrenees|Great Swiss Mountain Dog|Hovawart|Kangal Shepherd Dog|Landseer|Leonberger|Mastino Napoletano|Miniature Pinscher|Newfoundland|Pinscher|Portuguese Watchdog|Pyrenean Mastiff|Rottweiler|Saint Bernard|Shar Pei|Standard Schnauzer|Tibetan Mastiff|Tornjak'),
  ...itens(3, 'Airedale Terrier|American Staffordshire Terrier|Australian Silky Terrier|Australian Terrier|Bedlington Terrier|Border Terrier|Bull Terrier|Cairn Terrier|Cesky Terrier|Dandie Dinmont Terrier|English Toy Terrier|Fox Terrier Smooth|Fox Terrier Wire|Glen of Imaal Terrier|Irish Terrier|Jack Russell Terrier|Kerry Blue Terrier|Lakeland Terrier|Manchester Terrier|Miniature Bull Terrier|Miniature Schnauzer|Norfolk Terrier|Norwich Terrier|Parson Russell Terrier|Scottish Terrier|Sealyham Terrier|Skye Terrier|Staffordshire Bull Terrier|Welsh Terrier|West Highland White Terrier|Yorkshire Terrier'),
  ...itens(4, 'Dachshund'),
  ...itens(5, 'Akita|Alaskan Malamute|American Akita|Basenji|Canaan Dog|Canadian Eskimo Dog|Chow Chow|Cirneco dell Etna|Eurasier|Finnish Lapphund|Finnish Spitz|Greenland Dog|Icelandic Sheepdog|Japanese Spitz|Kai Ken|Karelian Bear Dog|Kishu Ken|Korea Jindo Dog|Norwegian Buhund|Norwegian Elkhound Black|Norwegian Elkhound Grey|Norwegian Lundehund|Pharaoh Hound|Podenco Canario|Podenco Ibicenco|Portuguese Podengo|Samoyed|Shiba Inu|Shikoku|Shikoku Ken|Siberian Husky|Thai Bangkaew Dog|Thai Ridgeback|Volpino Italiano|Xoloitzcuintli'),
  ...itens(6, 'American Foxhound|Ariegeois|Basset Artesien Normand|Basset Bleu de Gascogne|Basset Fauve de Bretagne|Basset Hound|Beagle|Beagle Harrier|Billy|Black and Tan Coonhound|Bloodhound|Bluetick Coonhound|Brazilian Tracker|Drever|English Foxhound|Finnish Hound|Gascon Saintongeois|Grand Basset Griffon Vendeen|Grand Bleu de Gascogne|Grand Griffon Vendeen|Griffon Bleu de Gascogne|Griffon Fauve de Bretagne|Hamiltonstovare|Hanoverian Scent Hound|Harrier|Otterhound|Petit Basset Griffon Vendeen|Plott Hound|Porcelaine|Rhodesian Ridgeback|Slovakian Hound|Swiss Hound'),
  ...itens(7, 'Bracco Italiano|Braque d Auvergne|Braque de l Ariege|Braque du Bourbonnais|Brittany Spaniel|Burgos Pointer|Czech Fousek|Drentsche Patrijshond|English Pointer|English Setter|French Spaniel|German Longhaired Pointer|German Shorthaired Pointer|German Wirehaired Pointer|Gordon Setter|Hungarian Vizsla|Irish Red and White Setter|Irish Setter|Italian Spinone|Large Munsterlander|Old Danish Pointer|Picardy Spaniel|Portuguese Pointer|Pudelpointer|Slovakian Wirehaired Pointer|Small Munsterlander|Stabyhoun|Weimaraner'),
  ...itens(8, 'American Cocker Spaniel|American Water Spaniel|Barbet|Chesapeake Bay Retriever|Clumber Spaniel|Curly Coated Retriever|English Cocker Spaniel|English Springer Spaniel|Field Spaniel|Flat Coated Retriever|Golden Retriever|Irish Water Spaniel|Labrador Retriever|Lagotto Romagnolo|Nederlandse Kooikerhondje|Nova Scotia Duck Tolling Retriever|Portuguese Water Dog|Sussex Spaniel|Welsh Springer Spaniel|Wetterhoun'),
  ...itens(9, 'Bichon Frise|Bolognese|Boston Terrier|Cavalier King Charles Spaniel|Chinese Crested Dog|Coton de Tulear|French Bulldog|Griffon Belge|Griffon Bruxellois|Havanese|Japanese Chin|King Charles Spaniel|Lhasa Apso|Maltese|Pekingese|Petit Brabancon|Poodle|Pug|Russian Toy|Shih Tzu|Tibetan Spaniel|Tibetan Terrier'),
  ...itens(10, 'Afghan Hound|Azawakh|Borzoi|Deerhound|Galgo Espanol|Greyhound|Hungarian Greyhound|Irish Wolfhound|Italian Greyhound|Polish Greyhound|Saluki|Sloughi|Whippet')
];

export const racasFelinas = [
  ...'Sem raça definida (SRD)|Abissínio|American Bobtail|American Curl|American Shorthair|American Wirehair|Balinese|Bengal|Birman|Bombaim|British Longhair|British Shorthair|Burmese|Burmilla|Chartreux|Colorpoint Shorthair|Cornish Rex|Cymric|Devon Rex|Donskoy|Egyptian Mau|Europeu de Pelo Curto|Exotic Shorthair|Havana Brown|Himalayan|Japanese Bobtail|Khao Manee|Korat|Kurilian Bobtail|LaPerm|Lykoi|Maine Coon|Manx|Mau Egípcio|Munchkin|Nebelung|Norueguês da Floresta|Ocicat|Oriental Shorthair|Persa|Peterbald|Pixiebob|Ragamuffin|Ragdoll|Russian Blue|Savannah|Scottish Fold|Selkirk Rex|Siamês|Siberiano|Singapura|Snowshoe|Somali|Sphynx|Thai|Tonkinese|Toyger|Turkish Angora|Turkish Van'
    .split('|')
    .map((nome) => ({ nome, especie: 'FELINO', grupoFci: null }))
];